### PR TITLE
frontend: Add statefulsets to frontend role

### PR DESCRIPTION
**Pull request by tsenart**
This is needed so that the endpoint package keeps working with it's latest changes.

### Checklist

* [ ] [CHANGELOG.md](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) updated
* [ ] [K8s Upgrade notes updated](https://github.com/sourcegraph/sourcegraph/blob/main/doc/admin/updates/kubernetes.md)
* [x] Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change:
* [x] All images have a valid tag and SHA256 sum

### CODE REVIEW

**Review by daxmc99 — APPROVED** [review]

**Comment by tsenart** [comment]
@daxmc99 does this change warrant a changelog entry or a note in upgrade notes?

**Comment by daxmc99** [comment]
I think the changelog should be fine. I'm not sure if it needs a specific callout in the Kubernetes upgrade notes is needed though

**Comment by tsenart** [comment]
> I think the changelog should be fine. I'm not sure if it needs a specific callout in the Kubernetes upgrade notes is needed though

@sourcegraph/distribution: Thoughts?

**Comment by tsenart** [comment]
https://github.com/sourcegraph/sourcegraph/pull/23959

**Pull request merged**
