### PR TITLE
renovate: disable go updates

### PR DESCRIPTION
**Pull request by keegancsmith**
It seems we often don't update the images due to hitting rate limits in
renovate around creating PRs. This seems to stem from it spending all
its effort on go updates, which we don't care about.

Copied from https://github.com/sourcegraph/renovate-config/blob/master/renovate.json#L43-L47

Test Plan: merge in master and see renovate behave correctly. Doesn't
affect end users.

### CODE REVIEW

**Review by burmudar — APPROVED** [review]

**Comment by keegancsmith** [comment]
@sourcegraph/dev-experience Can someone force merge this? CI is broken until we get the latest version of sourcegraph in this repo, renovate seems to rarely run for what we care about until this PR is merged.

Alternatively, do you guys have magic to manually update all the tags and not rely on renovate? I remember sg tool doing this, but I am on shitty coffeeshop wifi at the moment :)

**Review by jhchabran — APPROVED** [review]

**Comment by burmudar** [comment]
I don't have to rights - @jhchabran can you force merge this ?

**Comment by jhchabran** [comment]
> @sourcegraph/dev-experience Can someone force merge this? CI is broken until we get the latest version of sourcegraph in this repo, renovate seems to rarely run for what we care about until this PR is merged.
> 
> Alternatively, do you guys have magic to manually update all the tags and not rely on renovate? I remember sg tool doing this, but I am on shitty coffeeshop wifi at the moment :)

@keegancsmith that's `sg ops` !

**Comment by jhchabran** [comment]
@keegancsmith see https://github.com/sourcegraph/deploy-sourcegraph/pull/4166

**Pull request merged**
