### PR TITLE
Revert "redis-store: revert pure-docker simplifications (#158)"

### PR DESCRIPTION
**Pull request by ggilmore**
This PR restores @slimsag's pure docker redis-store simplifications that were reverted in https://github.com/sourcegraph/deploy-sourcegraph/pull/158 due to file permission issues. 

Bumping the `redis-store` and `redis-cache` images to the ones from https://github.com/sourcegraph/infrastructure/pull/1425 seems to fix https://github.com/sourcegraph/sourcegraph/issues/1761.

---

With https://github.com/sourcegraph/deploy-k8s-helper, I've tried the following upgrade paths: 

|                                    Old Version                                    |                               New Version                               | Works? |
|:---------------------------------------------------------------------------------:|:-----------------------------------------------------------------------:|:------:|
|      [(this PR)](https://github.com/sourcegraph/deploy-sourcegraph/pull/216)      |                                   N/A                                   |   Yes  |
|  [v3.1.2](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v3.1.2)  | [(this PR)](https://github.com/sourcegraph/deploy-sourcegraph/pull/216) |   Yes  |
| [v2.13.5](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v2.13.5) | [(this PR)](https://github.com/sourcegraph/deploy-sourcegraph/pull/216) |   Yes  |

@reviewers please try out these upgrades on your own to double check this

---

For https://github.com/sourcegraph/sourcegraph/issues/3254, do we know: 

1. What `2.x` version were they using beforehand?
1. Did they make any customizations to the `securityContext.runAsUser` setting?
1. Was `redis-cache` actually the broken deployment, or was it `redis-store`?

Note: I've not been able to reproduce https://github.com/sourcegraph/sourcegraph/issues/3254  when I tried the following upgrade paths:

|                                    Old Version                                    |                               New Version                               | Works? |
|:---------------------------------------------------------------------------------:|:-----------------------------------------------------------------------:|:------:|
|  [v2.13.5](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v2.13.5)  | [v3.1.2](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v3.1.2) |   Yes  |
|  [v2.12.3](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v2.12.3)  | [v3.1.2](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v3.1.2) |   Yes  |
|  [v2.12.3](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v2.12.3)  | [v3.2.2](https://github.com/sourcegraph/deploy-sourcegraph/releases/tag/v3.1.2) |   Yes  |

So, it's difficult to know whether or not this PR actually fixes https://github.com/sourcegraph/sourcegraph/issues/3254

### CODE REVIEW

**Comment by slimsag** [comment]
I left comments in https://github.com/sourcegraph/infrastructure/pull/1425

**Comment by slimsag** [comment]
@ggilmore Can we land this in 3.3?

**Comment by ggilmore** [comment]
@slimsag @keegancsmith PTAL, I've updated the PR.

**Comment by ggilmore** [comment]
@slimsag @keegancsmith Could you sign off on this when you get a chance? I removed the `Fixes: https://github.com/sourcegraph/sourcegraph/issues/3254` from the issue body.

**Pull request merged**
