### PR TITLE
Update sourcegraph/postgres-12.6 images to latest

### PR DESCRIPTION
**Pull request by andreeleuterio**
This PR updates images that use sourcegraph/postgres-12

[_Created by Sourcegraph batch change `andre/update-postgres12.6-base-images`._](https://k8s.sgdev.org/users/andre/batch-changes/update-postgres12.6-base-images)

### CODE REVIEW

**Review by daxmc99 — COMMENTED** [review]
Hmm, I'm not sure if renovate will update this

**Comment by andreeleuterio** [comment]
@daxmc99 did renovate update it before this change?

**Comment by daxmc99** [comment]
We previously didn't build Postgres 12 as part of CI so there was no image to update

**Review by daxmc99 — APPROVED** [review]
These concerns shouldn't block merging but @sourcegraph/distribution will need to be aware of this for the next release

**Pull request merged**
