### PR TITLE
release: sourcegraph@5.0.0

### PR DESCRIPTION
**Pull request by coury-clark**
This pull request is part of the Sourcegraph 5.0.0 release.

* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48131)

### Test plan

CI checks in this repository should pass, and a manual review should confirm if the generated changes are correct.

### CODE REVIEW

**Review by BolajiOlajide — APPROVED** [review]
Quick glance review. 👀

**Review by camdencheek — APPROVED** [review]

**Review by camdencheek — COMMENTED** [review]
looks like integration tests are failing for real?

**Comment by coury-clark** [comment]
@camdencheek yeah looks like a similar problem to last month where the test is out of date with src-cli, but will check

**Comment by coury-clark** [comment]
@camdencheek turns out this was a real issue, src-cli has an incompatibility in 5.0 with the `src validate` command. Since this command is behind an experimental flag and there is a quick workaround to upgrade to the upcoming 5.0.3 src-cli, we are disabling the test on this branch and proceeding with the release

**Pull request merged**
