### PR TITLE
move base to subdir to avoid kustomization.yaml

### PR DESCRIPTION
**Pull request by uwedeportivo**
avoids the complications with kustomization.yaml by moving the resource files into subdir and referencing them directly when doing kubectl apply -f

### CODE REVIEW

**Comment by uwedeportivo** [comment]
https://gravitational.com/blog/kubernetes-kustomize-kep-kerfuffle/

**Comment by uwedeportivo** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/738#issuecomment-458699417

**Comment by beyang** [comment]
Will this cause any merge conflicts with forks that have made changes to files in `base`? (I.e., is git smart enough to deal with renames in this case?)

**Comment by uwedeportivo** [comment]
superseded by https://github.com/sourcegraph/deploy-sourcegraph/pull/589

**Pull request closed without merging**
