### PR TITLE
all: update images to latest insiders tag

### PR DESCRIPTION
**Pull request by jhchabran**
Manual image updates, as requested by @keegancsmith 

### Checklist

* [ ] [CHANGELOG.md](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) updated
* [ ] [K8s Upgrade notes updated](https://github.com/sourcegraph/sourcegraph/blob/main/doc/admin/updates/kubernetes.md)
* [ ] Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change:
* [ ] All images have a valid tag and SHA256 sum

### Test plan

Should pass CI

### CODE REVIEW

**Comment by sanderginn** [comment]
Is there a reason all the image tags were changed to non-`insiders` builds? The [dev docs](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md#docker-images) mention to use `insiders`

**Review by sanderginn — CHANGES_REQUESTED** [review]
Is there a reason all the image tags were changed to non-`insiders` builds? The [dev docs](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md#docker-images) mention to use `insiders`

**Comment by jhchabran** [comment]
Ah, I probably ran the wrong command in `sg ops`, let me check 🙏

**Review by sanderginn — APPROVED** [review]

**Review by keegancsmith — CHANGES_REQUESTED** [review]
There are pure whitespace changes included in here which shouldn't land, those will just cause unnecessary conflicts in forks.

**Comment by keegancsmith** [comment]
I'll fix up, thank you so much! Also wanna target master so we can unblock all PRs :)

**Review by keegancsmith — APPROVED** [review]
LGTM. From removing non-tag changes I've seen that we have two images which are not tracking insiders: redis-exporter and pgsql. That will be to fix for another day.

**Comment by keegancsmith** [comment]
So CI was failing with the same error, that src-cli couldn't unmarshal the version string. Insiders is pointing to a commit from 2 hours ago, I wonder if it still isn't fixed? https://github.com/sourcegraph/sourcegraph/commit/c64dfe3668d00cfc11e0e5e31d07af040ed693b8

I see the version endpoint has had quite a bit of refactoring, I wonder if this is a real error in latest sourcegraph since the src-cli being using in CI is quite old `3.35.1`. cc @efritz @LawnGnome

**Comment by keegancsmith** [comment]
Alright, I manually tested that commit, and the version endpoint looks good to me. So I think what is actually happening here is src-cli is hitting dot-com endpoint, not the integration test endpoint! And dot-com hasn't had a deploy since the 25th, so still has the bad commit. I'll see if I can fix the test, but hopefully should sort itself out once dotcom gets some love.

**Pull request merged**
