### PR TITLE
DO NOT MERGE: Remove all references to lsp-proxy and xlang-go's gitserver dependency 

### PR DESCRIPTION
**Pull request by ggilmore**
This will be the impact of the things that you are working on. You should test the impact of your changes by trying to deploy this branch and seeing if your instance still works.

### CODE REVIEW

**Comment by keegancsmith** [comment]
Won't this break functionality in our current state?

**Comment by chrismwendt** [comment]
Right, this can't be merged yet. I'm working on moving lsp-proxy into each language server's Docker container, which is a prerequisite.

**Comment by nicksnyder** [comment]
Can we merge this now?

**Comment by chrismwendt** [comment]
Oh yup, I forgot about this one. I'll resolve whatever conflicts were created by https://github.com/sourcegraph/deploy-sourcegraph/pull/152 and merge this.

**Comment by chrismwendt** [comment]
Never mind, there were no real changes to be made after #152

**Pull request closed without merging**
